allowBuilds:
  '@parcel/watcher': true
  '@sentry/cli': true
  bcrypt: true
  browser-tabs-lock: true
  esbuild: true
  unrs-resolver: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@sentry/cli'
  - bcrypt
  - browser-tabs-lock
  - esbuild
  - unrs-resolver

overrides:
  nodemailer: ^9.0.1
  path-to-regexp: ^6.3.0
  ini: ^1.3.6
  minimatch: ^10.2.3
  nodemailer: ^9.0.1
  tar: ^7.5.16
  undici: ^6.27.0
  handlebars: "^4.7.9"
  flatted: "^3.4.2"
  rollup: "^4.59.0"
