allowBuilds:
  '@parcel/watcher': true
  '@sentry/cli': true
  bcrypt: true
  browser-tabs-lock: true
  esbuild: true
  unrs-resolver: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@sentry/cli'
  - bcrypt
  - browser-tabs-lock
  - esbuild
  - unrs-resolver

overrides:
  handlebars: "^4.7.9"
  flatted: "^3.4.2"
  rollup: "^4.59.0"
