export const publicPaths = [
    '/api/auth/login',
    '/api/auth/register',
    '/api/auth/auth0-login',
    '/api/auth/auth0-connections',
    '/api/auth/oauth-authorize',
    '/api/auth/oauth-callback',
    '/api/auth/oauth-config',
    '/api/auth/forgot-password',
    '/api/auth/reset-password',
    '/api/afdian/webhook',
    '/api/cron',
    '/api/health',

    '/login',
    '/about',
    '/register',
    '/forgot-password',
    '/reset-password',
    '/callback',
    '/auth0-callback',
    '/oauth-callback',
]
